name: azlens
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - scipy=1.17.1
  - pandas=3.0.5
  - matplotlib=3.11.0
  - pyyaml=6.0.3
  - pytest=9.0.3
  - pip
  - pip:
      - colossus==1.4.0
