"""Seeded centering-offset realizations for the publication population.

This module contains no lensing calculation.  It only implements the
common-random-number Rayleigh offset stream specified for the paper-specific
population experiment.  Offset angles are measured from the projected major
axis and are therefore named ``phi_offset`` rather than ``alpha``.
"""
from __future__ import annotations

from dataclasses import dataclass
import hashlib

import numpy as np
from numpy.typing import ArrayLike, NDArray

DEFAULT_OFFSET_BASE_SEED = 20260816
DEFAULT_SIGMA_D = (0.0, 0.02, 0.05, 0.08)


def _size(size: int) -> int:
    n = int(size)
    if n < 1:
        raise ValueError("size must be at least one")
    return n


def _grid_index(grid_index: int) -> int:
    idx = int(grid_index)
    if idx < 0:
        raise ValueError("grid_index must be non-negative")
    return idx


def float64_sha256(values: ArrayLike) -> str:
    """SHA-256 of a C-contiguous little-endian float64 representation."""
    arr = np.ascontiguousarray(np.asarray(values, dtype="<f8"))
    return hashlib.sha256(arr.tobytes()).hexdigest()


@dataclass(frozen=True)
class OffsetRealization:
    """Reusable two-dimensional centering-offset draw for one grid."""

    grid_index: int
    base_seed: int
    rayleigh_unit: NDArray[np.float64]
    phi_offset: NDArray[np.float64]

    @property
    def size(self) -> int:
        return int(self.rayleigh_unit.size)

    @property
    def seed_sequence_entropy(self) -> tuple[int, int]:
        return (int(self.base_seed), int(self.grid_index))

    @property
    def bit_generator_name(self) -> str:
        # The arrays were generated by default_rng.  This property documents the
        # current bit generator without requiring the Generator object to be kept.
        return "PCG64"

    def amplitudes(self, sigma_d: float) -> NDArray[np.float64]:
        sigma = float(sigma_d)
        if not np.isfinite(sigma) or sigma < 0.0:
            raise ValueError("sigma_d must be finite and non-negative")
        return np.asarray(sigma * self.rayleigh_unit)

    def amplitude_matrix(self, sigma_d: ArrayLike = DEFAULT_SIGMA_D) -> NDArray[np.float64]:
        sigma = np.asarray(sigma_d, dtype=np.float64).reshape(-1)
        if sigma.size == 0 or np.any(~np.isfinite(sigma)) or np.any(sigma < 0.0):
            raise ValueError("sigma_d must contain finite non-negative values")
        return np.asarray(sigma[:, None] * self.rayleigh_unit[None, :])

    def digest_summary(self) -> dict[str, str]:
        return {
            "rayleigh_unit_sha256_float64_le": float64_sha256(self.rayleigh_unit),
            "phi_offset_sha256_float64_le": float64_sha256(self.phi_offset),
            "d_over_r200_sha256_float64_le": float64_sha256(self.amplitude_matrix()),
        }


def draw_offset_realization(
    *,
    size: int,
    grid_index: int,
    base_seed: int = DEFAULT_OFFSET_BASE_SEED,
) -> OffsetRealization:
    """Draw the publication offset stream for one grid.

    The stream is deliberately independent of the halo-population generator:
    ``SeedSequence([base_seed, grid_index])`` selects the grid.  The same unit
    Rayleigh variate and ``phi_offset`` are reused for every nonzero ``sigma_d``
    value, every source plane, and the later far-background alignment test.
    """
    n = _size(size)
    idx = _grid_index(grid_index)
    sequence = np.random.SeedSequence([int(base_seed), idx])
    rng = np.random.default_rng(sequence)
    u = rng.random(n)
    rayleigh_unit = np.sqrt(-2.0 * np.log1p(-u))
    phi_offset = rng.uniform(0.0, 2.0 * np.pi, size=n)
    return OffsetRealization(
        grid_index=idx,
        base_seed=int(base_seed),
        rayleigh_unit=np.asarray(rayleigh_unit, dtype=np.float64),
        phi_offset=np.asarray(phi_offset, dtype=np.float64),
    )
